server {
    listen       80 default_server;
    server_name  localhost _;
    root         /usr/share/nginx/html;
    index dc/frontend/frontend.php dc/admin/admin.php index.php index.html;
	rewrite_log on;

    location / {
        try_files $uri /dc/frontend/frontend.php?$query_string;
        autoindex off;
    }

    location /dc/ {
        index admin.php index.html index.htm;
        try_files $uri /dc/admin/admin.php?$query_string;
        autoindex off;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }


    location ~* \.(js|jpg|png|css)$ {
        expires 30d;
    }
}