<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style type="text/css">
        body,td,th { font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: #000000; }
        h1 { font-size: 18px; color: <?=$GLOBALS['shop_setup']['mail_color']?>; margin: 0; padding: 0;margin-bottom: 10px}
        h2 { font-size: 16px; color: <?=$GLOBALS['shop_setup']['mail_color']?>; margin: 0; padding: 0;}
        h3,h4,h5 { font-size: 14px; color: <?=$GLOBALS['shop_setup']['mail_color']?>; margin: 0; padding: 0;}
        .small { font-size: 10px; }
    </style>
</head>
<body style='text-align:center' align='center'>
    <table border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
            <td>
                <?php echo $this->model->mainContent ?>
            </td>
        </tr>
    </table>
</body>
</html>