#include <idp.iss>
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{39FFAF5E-F0E2-40E5-BF8C-BAB5A214F6E7}
AppName=dynamic commerce ShopControl
AppVersion=1.0
;AppVerName=dynamic commerce ShopControl 1.0
AppPublisher=dynamic commerce GmbH
AppPublisherURL=https://www.dc-solution.de/
AppSupportURL=https://www.dc-solution.de/
AppUpdatesURL=https://www.dc-solution.de/
DefaultDirName={pf}\dynamic commerce GmbH\dynamic commerce ShopControl
DefaultGroupName=dynamic commerce GmbH\dynamic commerce ShopControl
DisableProgramGroupPage=yes
OutputDir=C:\gitRepos\mysydeshop-nav2016\internal\ClientAddIn\2009R2 Classic\
OutputBaseFilename=dynamic_commerce_shop_control
SetupIconFile=C:\gitRepos\mysydeshop-nav2016\internal\ClientAddIn\2009R2 Classic\DynamicCommerceShopControl\DynamicCommerceShopControl\Symbol_dynamic_commerce_gr_n.ico
UninstallDisplayIcon={app}\Symbol_dynamic_commerce_gr_n.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Files]
Source: "C:\gitRepos\mysydeshop-nav2016\internal\ClientAddIn\2009R2 Classic\DynamicCommerceShopControl\DynamicCommerceShopControl\bin\Debug\DynamicCommerceShopControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\gitRepos\mysydeshop-nav2016\internal\ClientAddIn\2009R2 Classic\DynamicCommerceShopControl\DynamicCommerceShopControl\bin\Debug\DynamicCommerceShopControl.tlb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\gitRepos\mysydeshop-nav2016\internal\ClientAddIn\2009R2 Classic\DynamicCommerceShopControl\DynamicCommerceShopControl\Symbol_dynamic_commerce_gr_n.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Code]
var netFrameworkInstallDir: string;

function GetNetFrameworkInstallDir(Param: string): String;
begin
  Result := netFrameworkInstallDir;
end;

function Framework45IsNotInstalled(): Boolean;
var
  bSuccess: Boolean;
  bSuccess2: Boolean;
  regVersion: Cardinal;
begin
  Result := True;
  bSuccess := RegQueryDWordValue(HKLM, 'Software\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', regVersion);
  if (True = bSuccess) and (regVersion >= 379893) then begin
    bSuccess2 := RegQueryStringValue(HKLM, 'Software\Microsoft\NET Framework Setup\NDP\v4\Full', 'InstallPath', netFrameworkInstallDir);
    if (True = bSuccess2) then begin
      Result := False;
    end;
  end;
end;

procedure InitializeWizard;
begin
  if Framework45IsNotInstalled() then
  begin
    idpAddFile('https://www.dc-solution.de/userdata/NDP452-KB2901907-x86-x64-AllOS-ENU.exe', ExpandConstant('{tmp}\NetFrameworkInstaller.exe'));
    idpDownloadAfter(wpReady);
  end;
end;

procedure InstallFramework;
var
  StatusText: string;
  ResultCode: Integer;
begin
  StatusText := WizardForm.StatusLabel.Caption;
  WizardForm.StatusLabel.Caption := 'Installing .NET Framework 4.5.2. This might take a few minutes...';
  WizardForm.ProgressGauge.Style := npbstMarquee;
  try
    if not Exec(ExpandConstant('{tmp}\NetFrameworkInstaller.exe'), '/passive /norestart', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then
    begin
      MsgBox('.NET installation failed with code: ' + IntToStr(ResultCode) + '.', mbError, MB_OK);
    end;
  finally
    WizardForm.StatusLabel.Caption := StatusText;
    WizardForm.ProgressGauge.Style := npbstNormal;

    DeleteFile(ExpandConstant('{tmp}\NetFrameworkInstaller.exe'));
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  case CurStep of
    ssPostInstall:
      begin
        if Framework45IsNotInstalled() then
        begin
          InstallFramework();
        end;
      end;
  end;
end;

[Run]
Filename: {code:GetNetFrameworkInstallDir}RegAsm.exe; Parameters: /tlb:{app}\DynamicCommerceShopControl.tlb /codebase {app}\DynamicCommerceShopControl.dll; WorkingDir: {app}; StatusMsg: Registering controls ...; Flags: runhidden 32bit; Check: Not IsWin64;
Filename: {code:GetNetFrameworkInstallDir}RegAsm.exe; Parameters: /tlb:{app}\DynamicCommerceShopControl.tlb /codebase {app}\DynamicCommerceShopControl.dll; WorkingDir: {app}; StatusMsg: Registering controls ...; Flags: runhidden 64bit; Check: IsWin64; 

[UninstallRun]
Filename: {code:GetNetFrameworkInstallDir}RegAsm.exe; Parameters: /unregister {app}\DynamicCommerceShopControl.dll; WorkingDir: {app}; StatusMsg: Unegistering controls ...; Flags: runhidden 32bit; Check: Not IsWin64;
Filename: {code:GetNetFrameworkInstallDir}RegAsm.exe; Parameters: /unregister {app}\DynamicCommerceShopControl.dll; WorkingDir: {app}; StatusMsg: Unegistering controls ...; Flags: runhidden 64bit; Check: IsWin64; 