{%orderHeader%}
<table class="cardform" border="0" cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td class="cardform_left">
            <div id="guest_select">
                {%orderTypeSelect%}
                <br>
                {%infoContentLeft%}
                <div id="secure_order">
                    <div id="secure_order_text"><h1>%securePaymentText%</h1>%sslEncryptedText%</div>
                    <div id="protection_order_text"><h1>%fullProtectionText%</h1>%yourPersonalDataText%</div>
                    <div id="quality_order_text"><h1>%qualityAssuranceText%</h1>%satisfactionGuaranteedText%</div>
                </div>
                <div id="voucher_info_order"><h2>%couponCodesText%</h2>%canBeUsedInStep3Text%</div>
            </div>
        </td>
        <td class="cardform_right">
            %detailsForm%
        </td>
    </tr>
    </tbody>
</table>